# Generated by Django 6.0.1 on 2026-02-05 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='fname',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.users'),
            preserve_default=False,
        ),
    ]
